version = 1

test_patterns = [
  "test/**",
  "test_integration/**",
  "test_*.py",
  "src_matlab/**"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
    "requirements.txt"
]

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"
enabled = true


